[tool.poetry]
name = "graphima"
version = "0.0.1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "~3.11"

# doc
markdown-include = "*"
mdx-truly-sane-lists = "*"
mkdocs = "*"
mkdocs-exclude = "*"
mkdocs-material = "*"
pygments = "*"
pymdown-extensions = "*"
